// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/expenses": {
    params: {};
  };
  "/dashboard/categories": {
    params: {};
  };
  "/dashboard/stats": {
    params: {};
  };
  "/logout": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/dashboard" | "/dashboard/expenses" | "/dashboard/categories" | "/dashboard/stats" | "/logout";
  };
  "./routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "./routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "./routes/dashboard/_layout.tsx": {
    id: "routes/dashboard/_layout";
    page: "/dashboard" | "/dashboard/expenses" | "/dashboard/categories" | "/dashboard/stats";
  };
  "./routes/dashboard/index.tsx": {
    id: "routes/dashboard/index";
    page: "/dashboard";
  };
  "./routes/dashboard/expenses.tsx": {
    id: "routes/dashboard/expenses";
    page: "/dashboard/expenses";
  };
  "./routes/dashboard/categories.tsx": {
    id: "routes/dashboard/categories";
    page: "/dashboard/categories";
  };
  "./routes/dashboard/stats.tsx": {
    id: "routes/dashboard/stats";
    page: "/dashboard/stats";
  };
  "./routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/./routes/_index.tsx");
  "routes/login": typeof import("./app/./routes/login.tsx");
  "routes/dashboard/_layout": typeof import("./app/./routes/dashboard/_layout.tsx");
  "routes/dashboard/index": typeof import("./app/./routes/dashboard/index.tsx");
  "routes/dashboard/expenses": typeof import("./app/./routes/dashboard/expenses.tsx");
  "routes/dashboard/categories": typeof import("./app/./routes/dashboard/categories.tsx");
  "routes/dashboard/stats": typeof import("./app/./routes/dashboard/stats.tsx");
  "routes/logout": typeof import("./app/./routes/logout.tsx");
};